name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: none
version: 4.0.3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
